### PR TITLE
Expand intro notebook.  MPI section to be expanded once NERSC is back.

### PR DESCRIPTION
**Pull request by tskisner**

### CODE REVIEW

**Comment by zonca** [comment]
@tskisner I get this error: `KeyError: 'toast.tests.env'` in the cell that runs the unit tests

**Comment by zonca** [comment]
nevermind I think it is the older TOAST version I have

**Comment by zonca** [comment]
I would split the cells into smaller cells, that makes it easier for people to experiment, for example the quaternion cell, the cache cell, even cell 4 could be split in 2 or 3.

**Comment by tskisner** [comment]
@zonca, yes the env test was recently added.  I can split the cells some more if you like, but will do that after the work on the satellite scanning.

**Comment by tskisner** [comment]
I split off the MPI example into a separate notebook.  Looking through the serial cells, these run in less than a second and the longest one is about 50 lines.  Is that really too long?  I don't see much benefit splitting it finer when the user can re-run the whole cell so fast.

**Comment by zonca** [comment]
@tskisner yes, it is too long, I don't understand what is printing what in the cell output. Anyway we can fix this later.

I still get `RuntimeError: "env" is not a valid test.` even with the latest `20191008` kernel. I assume you will update the kernel.

I'll merge it

**Pull request merged**
