### PR TITLE
Sky signal simulation lesson

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by zonca** [comment]
can you please check how I get the angles in the `timedomain` notebook? is there a better way?

**Comment by tskisner** [comment]
By angles, you mean that lat and lon?  You have the full quaternions for every detector, so you can just do:
```
import toast.qarray as qa
theta, phi, pa = qa.to_angles(tod.read_pntg(detector="signal_0A"))[:num]
lat = (np.pi / 2) - theta 
```

**Comment by tskisner** [comment]
Wow, I see why you thought my cells were too big- you have almost one line per cell.  I never thought to group things that fine-grained.  I have some work to do to match the tiny-cell style in the other lessons...

These lessons look fine though, merge when you like.

**Comment by zonca** [comment]
I have an issue with binning, I can remove that part if we don't figure it out, but maybe it is something simple.

**Comment by zonca** [comment]
the hitmap from simscan is 
image

but if I get pixels and accumulate it myself, I get a strange hitmap:

image

this is in the last version of the `timedomain` notebook if you want to run it yourself @tskisner

**Comment by zonca** [comment]
@tskisner nevermind, that was just the first observation

**Comment by zonca** [comment]
@tskisner the logging in the `timedomain` doesn't work, I have several `log.debug` in the operator but they don't show up even if I set it in the environment

**Comment by zonca** [comment]
ok, merging this, only issue is that there is no logging output, but that is minor.
will test tomorrow with new kernel.

**Pull request merged**
